### PR TITLE
Minor changes

### PR DESCRIPTION
**Pull request by ghost**
More to come in future.

### CODE REVIEW

**Comment by di48l069** [comment]
@theouteredge With that .gitignore file it prevents all that crappy .suo files and so on from getting committed you should remove the old ones from repository as well as packages because nuget restores them locally on build just nice to clean up your repro that's if you decide to accept my pull I will make more pulls as soon as I'm free.

**Comment by theouteredge** [comment]
Accepted and Merged in. Thanks! :+1:

**Comment by ghost** [comment]
@theouteredge  Thanks busy with a few new changes, please don't forget to update it on nuget

**Comment by theouteredge** [comment]
published 1.7.3

**Pull request merged**
